export const ERROR_CODES = {
  // General errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  
  // Auth errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  
  // Tenant errors
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_LIMIT_REACHED: 'TENANT_LIMIT_REACHED',
  
  // Product errors
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  
  // Order errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  SHIPPING_NOT_AVAILABLE: 'SHIPPING_NOT_AVAILABLE',
  
  // Customer errors
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  
  // Swiss specific errors
  INVALID_SWISS_POSTAL_CODE: 'INVALID_SWISS_POSTAL_CODE',
  INVALID_VAT_NUMBER: 'INVALID_VAT_NUMBER',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES = {
  [ERROR_CODES.INTERNAL_ERROR]: 'An internal error occurred',
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.UNAUTHORIZED]: 'Unauthorized access',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.RATE_LIMITED]: 'Rate limit exceeded',
  
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid credentials',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid token',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email not verified',
  [ERROR_CODES.ACCOUNT_LOCKED]: 'Account is locked',
  
  [ERROR_CODES.TENANT_NOT_FOUND]: 'Tenant not found',
  [ERROR_CODES.TENANT_SUSPENDED]: 'Tenant is suspended',
  [ERROR_CODES.TENANT_LIMIT_REACHED]: 'Tenant limit reached',
  
  [ERROR_CODES.PRODUCT_NOT_FOUND]: 'Product not found',
  [ERROR_CODES.INSUFFICIENT_INVENTORY]: 'Insufficient inventory',
  [ERROR_CODES.PRODUCT_INACTIVE]: 'Product is inactive',
  
  [ERROR_CODES.ORDER_NOT_FOUND]: 'Order not found',
  [ERROR_CODES.ORDER_ALREADY_PROCESSED]: 'Order already processed',
  [ERROR_CODES.PAYMENT_FAILED]: 'Payment failed',
  [ERROR_CODES.SHIPPING_NOT_AVAILABLE]: 'Shipping not available',
  
  [ERROR_CODES.CUSTOMER_NOT_FOUND]: 'Customer not found',
  [ERROR_CODES.INVALID_ADDRESS]: 'Invalid address',
  
  [ERROR_CODES.INVALID_SWISS_POSTAL_CODE]: 'Invalid Swiss postal code',
  [ERROR_CODES.INVALID_VAT_NUMBER]: 'Invalid VAT number',
  [ERROR_CODES.PAYMENT_GATEWAY_ERROR]: 'Payment gateway error',
} as const;